# fly.toml app configuration file generated for substreams on 2023-05-01T09:22:09+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "substreams"
primary_region = "fra"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  SUBSTREAMS_HOSTNAME = "::"
  SUBSTREAMS_PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 200

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
